# This is a basic workflow to help you get started with Actions

name: action_test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  action_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: clone repository
        run:
          git clone https://github.com/yehhungwei/myrepo.git
          cd myrepo

      # Runs a set of commands using the runners shell
      - name: install test
        run: pip install test

      - name: run test
        run: test
   